GET http://localhost:8001/api/pizza

###

POST http://localhost:8001/api/pizza
Content-Type: application/json

{
  "idPizza": 0,
  "ingredients": [
    {
      "id_ingrediente": 2,
      "cantidad": 1
    },
    {
      "id_ingrediente": 4,
      "cantidad": 1
    },
    {
      "id_ingrediente": 23,
      "cantidad": 1
    },
    {
      "id_ingrediente": 29,
      "cantidad": 1
    }
  ],
  "base": 23,
  "salsa": 29
}

###

POST http://localhost:8001/api/pizza?idPizza=0